version: '3'
services:
  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    ports:
      - 4001:4001
      - 8080:8080
      - "127.0.0.1:5001:5001"
    volumes:
      - ipfs:/data/ipfs
  honeycomb:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - ipfshost=ipfs
      - ipfsprotocol=http
      - ipfsport=5001
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    stdin_open: true
    tty: true
volumes:
  ipfs:

networks:
  honeycomb:
